<?xml version="1.0" encoding="utf-8"?>
<Database Name="WebCrawler" Class="WebCrawlerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MMARINOV-PC;Initial Catalog=WebCrawler;Persist Security Info=True;User ID=MMarinov" SettingsObjectName="DALWebCrawler.Properties.Settings" SettingsPropertyName="WebCrawlerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Words" Member="Words">
    <Type Name="Word">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WordName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Word_WordsInFile" Member="WordsInFiles" ThisKey="ID" OtherKey="WordID" Type="WordsInFile" />
    </Type>
  </Table>
  <Table Name="dbo.WordsInFiles" Member="WordsInFiles">
    <Type Name="WordsInFile">
      <Column Name="WordID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FileID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Word_WordsInFile" Member="Word" ThisKey="WordID" OtherKey="ID" Type="Word" IsForeignKey="true" />
      <Association Name="File_WordsInFile" Member="File" ThisKey="FileID" OtherKey="ID" Type="File" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Statistics]" Member="Statistics">
    <Type Name="Statistic">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Words" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FoundTotalLinks" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FoundValidLinks" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CrawledTotalLinks" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CrawledSuccessfulLinks" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ProcessDescription" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Files" Member="Files">
    <Type Name="File">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(2500) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ImportantWords" Type="System.String" DbType="NVarChar(2500) NOT NULL" CanBeNull="false" />
      <Column Name="WeightedWords" Type="System.String" DbType="NVarChar(2500)" CanBeNull="true" />
      <Column Name="FileType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="File_WordsInFile" Member="WordsInFiles" ThisKey="ID" OtherKey="FileID" Type="WordsInFile" />
    </Type>
  </Table>
  <Function Name="dbo.sp_TruncateAllTables" Method="sp_TruncateAllTables">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_InsertFile" Method="sp_InsertFile">
    <Parameter Name="URL" Parameter="uRL" Type="System.String" DbType="NVarChar(2500)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="ImportantWords" Parameter="importantWords" Type="System.String" DbType="NVarChar(2500)" />
    <Parameter Name="WeightedWords" Parameter="weightedWords" Type="System.String" DbType="NVarChar(2500)" />
    <Parameter Name="FileType" Parameter="fileType" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="ID" Parameter="iD" Type="System.Int64" DbType="BigInt" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_InsertWordInFile" Method="sp_InsertWordInFile">
    <Parameter Name="WordID" Parameter="wordID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FileID" Parameter="fileID" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Count" Parameter="count" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_InsertWord" Method="sp_InsertWord">
    <Parameter Name="WordName" Parameter="wordName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ID" Parameter="iD" Type="System.Int64" DbType="BigInt" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_CopyDBByRestore" Method="sp_CopyDBByRestore">
    <Parameter Name="BackupFile" Parameter="backupFile" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="DestinationDB" Parameter="destinationDB" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="RestoreFileNoExtension" Parameter="restoreFileNoExtension" Type="System.String" DbType="VarChar(2000)" />
    <Return Type="System.Int32" />
  </Function>
</Database>